[package]

name = "neural"
version = "0.0.1"
authors = [ "jim@barkingmousestudio.com" ]

[dependencies]

wheel_timer = "0.2.1"
csv = "0.12.15"

[dependencies.rand]

git = "https://github.com/rust-lang/rand.git"

[lib]

name = "neural"

[profile.test]
opt-level = 0  # Controls the --opt-level the compiler builds with

[profile.bench]
opt-level = 3  # Controls the --opt-level the compiler builds with