[package]

name = "neural"
version = "0.0.1"
authors = [ "jim@barkingmousestudio.com" ]

[dependencies]
wheel_timer = "0.2.2"
rand = "0.1.4"

[dev-dependencies]
csv = "0.12.19"

[lib]

name = "neural"
